INSERT INTO worker (name, birthday, level, salary) VALUES ('Oleg','1982-12-23','Trainee',500);
INSERT INTO worker (name, birthday, level, salary) VALUES ('Victoria','1995-06-18','Senior',6000);
INSERT INTO worker (name, birthday, level, salary) VALUES ('Nataly','1962-12-01','Middle',2500);
INSERT INTO worker (name, birthday, level, salary) VALUES ('Denys','1991-06-09','Trainee',600);
INSERT INTO worker (name, birthday, level, salary) VALUES ('Dmytro','2001-08-28','Junior',1500);
INSERT INTO worker (name, birthday, level, salary) VALUES ('Darya','2000-08-19','Middle',3600);
INSERT INTO worker (name, birthday, level, salary) VALUES ('Stepan','1995-09-04','Senior',5000);
INSERT INTO worker (name, birthday, level, salary) VALUES ('Anna','2000-01-06','Senior',5700);
INSERT INTO worker (name, birthday, level, salary) VALUES ('Ruslan','1974-05-27','Middle',3000);
INSERT INTO worker (name, birthday, level, salary) VALUES ('Olena','1971-04-10','Trainee',750);

INSERT INTO client (name) VALUES ('Julio');
INSERT INTO client (name) VALUES ('James');
INSERT INTO client (name) VALUES ('Anastasia');
INSERT INTO client (name) VALUES ('Frederico');
INSERT INTO client (name) VALUES ('Orlando');

INSERT INTO project (client_id, start_date, finish_date) VALUES (3, '2019-08-14', '2021-11-02');
INSERT INTO project (client_id, start_date, finish_date) VALUES (1, '2020-12-23', '2023-12-23');
INSERT INTO project (client_id, start_date, finish_date) VALUES (2, '2021-10-16', '2023-01-20');
INSERT INTO project (client_id, start_date, finish_date) VALUES (1, '2022-06-08', '2024-08-21');
INSERT INTO project (client_id, start_date, finish_date) VALUES (5, '2018-03-09', '2027-09-16');
INSERT INTO project (client_id, start_date, finish_date) VALUES (2, '2020-07-24', '2021-12-29');
INSERT INTO project (client_id, start_date, finish_date) VALUES (4, '2019-01-19', '2026-10-03');
INSERT INTO project (client_id, start_date, finish_date) VALUES (1, '2023-02-01', '2023-10-07');
INSERT INTO project (client_id, start_date, finish_date) VALUES (3, '2018-07-08', '2025-09-23');
INSERT INTO project (client_id, start_date, finish_date) VALUES (2, '2021-11-30', '2023-05-17');

INSERT INTO project_worker (project_id, worker_id) VALUES (1,5);
INSERT INTO project_worker (project_id, worker_id) VALUES (1,9);
INSERT INTO project_worker (project_id, worker_id) VALUES (2,6);
INSERT INTO project_worker (project_id, worker_id) VALUES (3,17);
INSERT INTO project_worker (project_id, worker_id) VALUES (1,15);
INSERT INTO project_worker (project_id, worker_id) VALUES (4,15);
INSERT INTO project_worker (project_id, worker_id) VALUES (4,3);
INSERT INTO project_worker (project_id, worker_id) VALUES (5,3);
INSERT INTO project_worker (project_id, worker_id) VALUES (5,4);
INSERT INTO project_worker (project_id, worker_id) VALUES (6,5);
INSERT INTO project_worker (project_id, worker_id) VALUES (6,6);
INSERT INTO project_worker (project_id, worker_id) VALUES (6,7);
INSERT INTO project_worker (project_id, worker_id) VALUES (7,8);
INSERT INTO project_worker (project_id, worker_id) VALUES (7,7);
INSERT INTO project_worker (project_id, worker_id) VALUES (7,9);
INSERT INTO project_worker (project_id, worker_id) VALUES (8,10);
INSERT INTO project_worker (project_id, worker_id) VALUES (8,14);
INSERT INTO project_worker (project_id, worker_id) VALUES (8,3);
INSERT INTO project_worker (project_id, worker_id) VALUES (8,4);
INSERT INTO project_worker (project_id, worker_id) VALUES (9,10);
INSERT INTO project_worker (project_id, worker_id) VALUES (9,8);
INSERT INTO project_worker (project_id, worker_id) VALUES (10,6);
INSERT INTO project_worker (project_id, worker_id) VALUES (10,11);
INSERT INTO project_worker (project_id, worker_id) VALUES (10,5);
